<?xml version="1.0"?>
<package format="2">
  <name>wsg50_simulation</name>
  <version>0.0.0</version>
  <description>The wsg50_simulation package</description>

  <maintainer email="nalt@todo.todo">nalt</maintainer>

  <license>BSD</license>

  <author>Nicolas Alt</author>
  <author>Robotnik</author>
  <author>Weiss Robotics</author>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>roscpp</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>std_srvs</build_depend>
  <build_depend>wsg50_common</build_depend>
  <build_depend>urdf</build_depend>

  <exec_depend>roscpp</exec_depend>
  <exec_depend>urdf</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>wsg50_common</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>gazebo_ros</exec_depend>

</package>
